version: '3.8'

services:
  postgres:
    container_name: giannaschool_db
    image: postgres:15.5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=giannaschool_db